#apiVersion: v1
#kind: Secret
#metadata:
#  name: controller-manager
#  namespace: runner-system
#type: Opaque
#data:
#  github_token: Z2hwX2d1aWxkYXl1a2F0aW9uX2F1dG9rZW4=

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner
  namespace: runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: hoanglh2/test
      labels:
        - sh-k8s-runner

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-deployment-autoscaler
  namespace: runner-system
spec:
  scaleDownDelaySecondsAfterScaleOut: 120
  scaleTargetRef:
    kind: RunnerDeployment
    name: runner
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - hoanglh2/test

